// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./cache.js')
  await import('./schema.js')

  test.resume()
}
